analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [

    path('analysis/input/', views.analysis_input, name='analysis_input'),
    #path('analysis/progress/', views.analysis_progress, name='analysis-progress'),

    path('perform_analysis/', views.perform_analysis, name='perform_analysis'),
  #  path('perform_analysis/<int:training_dataset_id>/<int:testing_dataset_id>/', views.perform_analysis,
   #      name='perform_analysis_with_dataset'),
   # path('perform_analysis/<int:dataset_id>/', views.perform_analysis, name='perform_analysis'),
    #path('results/<int:dataset_id>/', views.analysis_result, name='analysis_result'),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Example path (update with your actual view)
    path('example/', views.example_view, name='example'),
]

datasets/urls.py
from django.urls import path
from . import views
from .views import download_dataset

app_name = 'datasets'

urlpatterns = [
    path('', views.dataset_list, name='dataset_list'),
    path('delete/<int:pk>/', views.dataset_delete, name='dataset_delete'),
    path('download/<int:dataset_id>/', download_dataset, name='download_dataset'),

]

finSentiments/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('', include('frontend.urls')),  # This will include the URL patterns from the frontend app
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),  # Include URLs from the users app
    path('datasets/', include('datasets.urls')),
    path('analysis/', include('analysis.urls')),
    path('reports/', include('reports.urls')),
    path('jobs/', include('jobs.urls')),
    path('api/', include('api.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views


app_name = 'frontend'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('submit-contact/', views.submit_contact, name='submit_contact'),
]

base/models.py
# models.py within 'base' app

from django.db import models
from django.utils import timezone
from users.models import CustomUser
from .middleware import GlobalRequestMiddleware


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, related_name="%(class)s_created", on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(CustomUser, related_name="%(class)s_updated", on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        user = GlobalRequestMiddleware.get_current_user()
        if user and not user.is_anonymous:
            if not self.pk:
                self.created_by = user
            self.updated_by = user
        super().save(*args, **kwargs)

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/includes/footer.html
{% load static %}
<footer class="footer bg-dark text-white py-4">
  <div class="container">
    <div class="row">
      <!-- Quick Links -->
      <div class="col-md-4 mb-3">
        <h5>Quick Links</h5>
        <ul class="list-unstyled">
          <li><a href="#" class="text-white">Home</a></li>
          <li><a href="#features" class="text-white">Features</a></li>
          <li><a href="#pricing" class="text-white">Pricing</a></li>
          <li><a href="#contact" class="text-white">Contact Us</a></li>
        </ul>
      </div>
      <!-- Contact Information -->
      <div class="col-md-4 mb-3">
        <h5>Contact Information</h5>
        <p>Information Security Lab, The Islamia Univeristy of Bahawalpur</p>
        <p>Email: info@finsentiments.com</p>
        <p>Phone: +92 300 6999824</p>
      </div>
      <!-- Social Media Icons -->
      <div class="col-md-4 mb-3">
        <h5>Follow Us</h5>
        <a href="#" class="text-white mr-2"><i class="fab fa-facebook-f"></i></a>
        <a href="#" class="text-white mr-2"><i class="fab fa-twitter"></i></a>
        <a href="#" class="text-white mr-2"><i class="fab fa-linkedin-in"></i></a>
        <a href="#" class="text-white"><i class="fab fa-instagram"></i></a>
      </div>
    </div>
    <!-- Footer Bottom -->
    <div class="text-center mt-4">
      <p>&copy; 2024 FinSentiments. All rights reserved.</p>
    </div>
  </div>

<!-- Script dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js"></script>
<!-- Optional: scripts.js for custom scripts -->
<script src="{% static 'js/scripts.js' %}"></script>
</footer>

base/templates/base/includes/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FinSentiments</title>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.css"/>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.css"/>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    </head>

base/templates/base/includes/navbar.html
{% load custom_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'frontend:home' %}">FinSentiments</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:home' %}">Home</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Financial Analysis
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'datasets:dataset_list' %}">Manage Datasets</a></li>
                        <li><a class="dropdown-item" href="{% url 'analysis:perform_analysis' %}">Perform Analysis</a></li>
                        <li><a class="dropdown-item" href="#">Analysis Results</a></li>
                        <li><a class="dropdown-item" href="#">Business Intelligence</a></li>
                        <li><a class="dropdown-item" href="#">Reports</a></li>
                        <li><a class="dropdown-item" href="#">Financial News Portals</a></li>
                    </ul>
                </li>


            {% endif %}



            <!-- Additional links can be added here -->

            <!-- Financial Tools -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownFinancialTools" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Financial Tools
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Portfolio Management</a></li>
                    <li><a class="dropdown-item" href="#">Market Analysis</a></li>
                    <li><a class="dropdown-item" href="#">Stock Screener</a></li>
                    <li><a class="dropdown-item" href="#">Option Analyzer</a></li>
                    <li><a class="dropdown-item" href="#">Risk Assessment</a></li>
                    <li><a class="dropdown-item" href="#">Fundamental Analysis</a></li>
                    <li><a class="dropdown-item" href="#">Technical Analysis</a></li>
                </ul>
            </li>

            <!-- Investment Planning -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownInvestmentPlanning" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Investment Planning
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Asset Allocation</a></li>
                    <li><a class="dropdown-item" href="#">Retirement Planner</a></li>
                    <li><a class="dropdown-item" href="#">Tax Planning</a></li>
                </ul>
            </li>

            {% if user|has_group:"Admin" %}
                <!-- Trading Tools -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownTradingTools" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Trading Tools
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Trading Simulator</a></li>
                        <li><a class="dropdown-item" href="#">Market News</a></li>
                        <li><a class="dropdown-item" href="#">Stock Alerts</a></li>
                    </ul>
                </li>
            {% endif %}

            <!-- Account and Transaction Management -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccountManagement" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account Management
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Account Overview</a></li>
                    <li><a class="dropdown-item" href="#">Transaction History</a></li>
                    <li><a class="dropdown-item" href="#">Funds Transfer</a></li>
                </ul>
            </li>

            <!-- User Profile and Settings -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUserProfile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User Profile
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <!-- Logout -->
                    <li class="dropdown-item"><a href="#">Logout</a></li>
                </ul>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:contact' %}">Contact</a>
            </li>
        </ul>
    </div>
</nav>